common/models/Cart.php
<?php


namespace common\models;

use yii\base\Model;

class Cart extends Model
{
    public function addToCart($product, $size, $qty = 1)
    {
//        echo 'Worked!';
        if (isset($_SESSION['cart'][$product->id])) {
            $_SESSION['cart'][$product->id]['qty'] += $qty;
        } else {
            $_SESSION['cart'][$product->id] = [
                'size' => $size,
                'qty' => $qty,
                'name' => $product->model,
                'price' => $product->price,
                'img' => $product->main_img,

            ];
        }
        $_SESSION['cart.qty'] = isset($_SESSION['cart.qty']) ? $_SESSION['cart.qty'] + $qty : $qty;
        $_SESSION['cart.sum'] = isset($_SESSION['cart.sum']) ? $_SESSION['cart.sum'] + $qty * $product->price : $qty * $product->price;
    }

    public function recalc($id)
    {

//            if (!isset($_SESSION['cart'][$product->id])) return false;

        $qtyMinus = $_SESSION['cart'][$id]['qty'];
        $sumMinus = $_SESSION['cart'][$id]['qty'] * $_SESSION['cart'][$id]['price'];
        $_SESSION['cart.qty'] -= $qtyMinus;
        $_SESSION['cart.sum'] -= $sumMinus;
        unset($_SESSION['cart'][$id]);

    }
}

frontend/controllers/CartController.php
<?php

namespace frontend\controllers;

use common\models\NpAreas;
use common\models\DeliveryType;
use common\models\NpWarehouses;

use common\models\Order;
use common\models\OrderItems;
use common\models\Product;
use common\models\Cart;

use common\models\UkrSettlements;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\Controller;
use Yii;
use yii\web\Response;
use PDO;

use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;



class CartController extends FrontendController
{
    public function actionAdd() {
        $id = Yii::$app->request->get('id');
        $size = Yii::$app->request->get('size');
        $qty = (int)Yii::$app->request->get('qty');
        $qty =!$qty ? 1 : $qty;
        $product = Product::findOne($id);
        if (empty($product)) return false;
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->addToCart($product, $size, $qty);
//        debug($session['cart']);
//        debug($session['cart.qty']);
//        debug($session['cart.sum']);
        if(!Yii::$app->request->isAjax) {
            return $this->redirect(Yii::$app->request->referrer);
        }
        $this->layout = false;
        return $this->render('cart-modal', compact("session"));
    }

    public function actionClear() {
        $session = Yii::$app->session;
        $session->open();
        $session->remove('cart');
        $session->remove('cart.qty');
        $session->remove('cart.sum');
        $this->layout = false;
        return $this->render('cart-modal', compact("session"));
    }

    public function actionDelItem() {
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->recalc($id);
        $this->layout = false;
        return $this->render('cart-modal', compact("session"));
    }

    public function actionView() {
//        '<pre>' . print_r(Yii::$app->params['adminEmail']) .  '</pre>';
        $session = Yii::$app->session;
        $session->open();
        $this->setMeta('Козина');

        $order = new Order();

        if ($order->load(Yii::$app->request->post()))  {

            $order->qty = $session['cart.qty'];
            $order->sum = $session['cart.sum'];
            if ($order->save()) {
                $this->saveOrderItems($session['cart'], $order->id);
                Yii::$app->session->setFlash('success', 'Ваш заказ принят. Наш Менджер вскоре с Вами свяжется');
                Yii::$app->mailer->compose('order', ['session' =>$session])
                    ->setFrom(['test@gmail.com'=>'voyts.com'])
                    ->setTo($order->email)
                    ->setSubject('Заказ')
////                ->setHtmlBody('<b>текст сообщения в формате HTML</b>')
                    ->send();
                Yii::$app->mailer->compose('order', ['session' =>$session])
                    ->setFrom(['test@gmail.com'=>'voyts.com'])
                    ->setTo(Yii::$app->params['adminEmail'])
                    ->setSubject('Заказ')
////                ->setHtmlBody('<b>текст сообщения в формате HTML</b>')
                    ->send();
                $session->remove('cart');
                $session->remove('cart.qty');
                $session->remove('cart.sum');
                return $this->refresh();
            } else {
                Yii::$app->session->setFlash('error', 'Ошибка оформления заказа.');
            }


        }
        return $this->render('view', compact('session', 'order'

        ));

    }

    public function actionShow() {
        $session = Yii::$app->session;
        $session->open();
        $this->layout = false;
        return $this->render('cart-modal', compact("session"));
    }

    protected function saveOrderItems($items, $order_id) {


        foreach ($items as $id =>$item) {
            $order_items = new OrderItems();
            $order_items->order_id = $order_id;
            $order_items->product_id = $id;
            $order_items->name = $item['name'];
            $order_items->price = $item['price'];
            $order_items->size = $item['size'];
            $order_items->qty_item = $item['qty'];
            $order_items->sum_item = $item['qty']*$item['price'];
            $order_items->save();
        }
    }



    public function actionDelivery()
    {
        $out = [];
        if (isset($_POST['depdrop_parents']))
        {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null)
            {
                $del_id = $parents[0];
                $deliveryList = DeliveryType::find()->where('id = :id', [':id' => $del_id])->limit(50)->all();
                $out = ArrayHelper::map($deliveryList, 'id', 'delivery_type');
                $result = [];
                $tmp_arr = [];
                foreach($out as $key => $value)
                {
                    $tmp_arr = ['id' => $key, 'delivery_type' => $value];
                    $result[] = $tmp_arr;
                }
                $areasN = asort($result);
                $facets = array();
                foreach ($result as $p) {
                    $facets[] = array(
                        'id' => $p['id'],
                        'name' => $p['delivery_type'],

                    );
                }

                $areasN = asort($facets);
                echo Json::encode(['output' => $facets, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }




    public function actionArea()
    {
        $out = [];
        if (isset($_POST['depdrop_parents']))
        {
            $parents = $_POST['depdrop_parents'];
            if ($parents[0] == 1)
            {
                $del_id = $parents[0];

//                '<pre>' . print_r($del_id)  . '</pre>';

                $delList = NpWarehouses::find()->where('delivery_id = :id', [':id' => $del_id])->limit(50)->all();
                $out = ArrayHelper::map($delList, 'area_id', 'settlement_area_description');
                $result = [];
                $tmp_arr = [];
                foreach($out as $key => $value)
                {
                    $tmp_arr = ['area_id' => $key, 'settlement_area_description' => $value];
                    $result[] = $tmp_arr;
                }
                $areasN = asort($result);
                $facets = array();
                foreach ($result as $p) {
                    $facets[] = array(
                        'id' => $p['area_id'],
                        'name' => $p['settlement_area_description'],

                    );
                }

                $areasN = asort($facets);
                echo Json::encode(['output' => $facets, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }

    public function actionCity()
    {
        $out = [];
        if (isset($_POST['depdrop_parents']))
        {


//                $del_id = $parents[0];

                $ids = $_POST['depdrop_parents'];
                $del_id = empty($ids[0]) ? null : $ids[0];
                $area_id = empty($ids[1]) ? null : $ids[1];
                if ($del_id == 1) {
                    $areaList = NpWarehouses::find()->where('area_id = :id', [':id' => $area_id])->limit(50)->all();
                $out = ArrayHelper::map($areaList, 'city_id', 'city_description');
                $result = [];
                $tmp_arr = [];
                foreach($out as $key => $value)
                {
                    $tmp_arr = ['city_id' => $key, 'city_description' => $value];
                    $result[] = $tmp_arr;
                }
                $areasN = asort($result);
                $facets = array();
                foreach ($result as $p) {
                    $facets[] = array(
                        'id' => $p['city_id'],
                        'name' => $p['city_description'],

                    );
                }

                $areasN = asort($facets);
                echo Json::encode(['output' => $facets, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }

    public function actionWarehouse() {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $ids = $_POST['depdrop_parents'];
            $del_id = empty($ids[0]) ? null : $ids[0];
            $area_id = empty($ids[1]) ? null : $ids[1];
            $subcat_id = empty($ids[2]) ? null : $ids[2];
            if ($del_id == 1) {
                $subcatList = NpWarehouses::find()->where('city_id = :id', [':id' => $subcat_id])->limit(50)->all();
                $out = ArrayHelper::map($subcatList, 'id', 'description');
                $result = [];
                $tmp_arr = [];
                foreach($out as $key => $value)
                {
                    $tmp_arr = ['city_id' => $key, 'city_description' => $value];
                    $result[] = $tmp_arr;
                }
                $areasN = asort($result);
                $facets = array();
                foreach ($result as $p) {
                    $facets[] = array(
                        'id' => $p['city_id'],
                        'name' => $p['city_description'],

                    );
                }

                $areasN = asort($facets);


                echo Json::encode(['output' => $facets, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }




    public function actionAreaTwo()
    {
        $out = [];
        if (isset($_POST['depdrop_parents']))
        {
            $parents = $_POST['depdrop_parents'];
            if ($parents[0]  == 3 || $parents[0] == 4)
            {
                $del_id = $parents[0];

frontend/views/cart/cart-modal.php
<?php use yii\helpers\Html;
use yii\helpers\Url;

if(!empty($session['cart'])): ?>
    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <thead>
            <tr>
                <th>Фото</th>
                <th>Наименование</th>
                <th>Размер</th>
                <th>Кол-во</th>
                <th>Цена</th>
                <th><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></th>
            </tr>
            </thead>
            <tbody>
<!--            <pre>--><?php //print_r($session['cart'])?><!--</pre>-->

            <?php foreach ($session['cart'] as $id => $item): ?>
                <tr>
                    <td><?= Html::img("/images/165x110{$item['img']}", ['alt' => $item['name'],'height' => 80])?></td>
                    <td><?= $item['name']?></td>

                    <?php if(!empty($item['size'])): ?>
                    <td><?= $item['size']?></td>
                    <?php else: ?>
                        <td></td>
                    <?php endif; ?>
                    <td><?= $item['qty']?></td>
                    <td><?= $item['price']?></td>
                    <td><span data-id="<?= $id ?>" class="glyphicon glyphicon-remove text-danger del-item" aria-hidden="true"></span></td>
                </tr>
            <?php endforeach; ?>
            <tr>
                <td colspan="4">Итого: </td>
                <td><?= $session['cart.qty']?> </td>

            </tr>
            <tr>
                <td colspan="4">На сумму: </td>
                <td><?= $session['cart.sum']?> </td>

            </tr>
            </tbody>
        </table>
    </div>
<?php else: ?>
    <h3>Корзина пуста</h3>
<?php endif; ?>
<script>     $('.del-item').on('click', function() {
        var id = $(this).data('id');
        console.log(id);
        $.ajax({
            url: '/cart/del-item',
            data: {id: id},
            type: 'GET',
            success: function (res) {
                if (!res) alert('Ошибка!');
                console.log(res);
                showCart(res);
            },
            error: function () {
                alert('Error!');
            }
        });
    });</script>

frontend/views/cart/get-cities.php
<?php

use backend\models\NpAreas;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
?>


<?php

$form = ActiveForm::begin();

$areasNp = NpAreas::find()->indexBy('ref')->asArray()->all();

echo $form->field($model, 'area')->dropDownList($areasNp, ['prompt' => 'Выберите область', 'ref' => 'region-selector']);
echo $form->field($model, 'city')->dropDownList([], ['prompt' => 'Выберите город', 'ref' => 'city-selector']);
echo Html::submitButton('Сохранить', ['class' => 'btn btn-success']);
ActiveForm::end();
?>
<script type="text/javascript">
    $('#region-selector').on('change', function () {
        $.ajax('/cart-controller/get-cities/' + this.value, {
            type: "POST",
            dataType: 'json',
            success: function (data) {
                if (data.success) {
                    $('#city-selector').empty();
                    $.each(data.cities, function (key, val) {
                        $('#city-selector').append('<option value="' + val.ref + '">' + val.description + '</option>');
                    });
                }
            }
        });
    });
</script>

frontend/views/cart/prod.php
<?php
use kartik\depdrop\DepDrop;

$catList = [
    1 => 'Electronics',
    2 => 'Books',
    3 => 'Home & Kitchen'
];

// Parent
echo $form->field($model, 'cat')->dropDownList($catList, ['id'=>'cat-id']);

// Child # 1
echo $form->field($model, 'subcat')->widget(DepDrop::classname(), [
    'options'=>['id'=>'subcat-id'],
    'pluginOptions'=>[
        'depends'=>['cat-id'],
        'placeholder'=>'Select...',
        'url'=>Url::to(['/site/subcat'])
    ]
]);

// Child # 2
echo $form->field($model, 'prod')->widget(DepDrop::classname(), [
    'pluginOptions'=>[
        'depends'=>['cat-id', 'subcat-id'],
        'placeholder'=>'Select...',
        'url'=>Url::to(['/site/prod'])
    ]
]);

frontend/views/cart/view.php
<?php


use common\models\City;
use common\models\DeliveryType;
use kartik\depdrop\DepDrop;
use LisDev\Delivery\NovaPoshtaApi2;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use common\models\Dropdown;
use common\models\NpWarehouses;

?>
<div class="container">
    <?php if(Yii::$app->session->hasFlash('success')): ?>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>

            <?php echo Yii::$app->session->getFlash('success'); ?>
        </div>
    <?php endif; ?>

    <?php if(Yii::$app->session->hasFlash('error')): ?>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <?php echo Yii::$app->session->getFlash('error'); ?>
        </div>
    <?php endif; ?>
    <?php if(!empty($session['cart'])): ?>
        <div class="table-responsive">
            <table class="table table-hover table-striped">
                <thead>
                <tr>
                    <th>Фото</th>
                    <th>Наименование</th>
                    <th>Размер</th>
                    <th>Кол-во</th>
                    <th>Цена</th>
                    <th>Сумма</th>
                    <th><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($session['cart'] as $id => $item): ?>
                    <tr>
                        <td><?= Html::img("/images/165x110{$item['img']}", ['alt' => $item['name'],'height' => 80])?></td>
                        <td><a href="<?= Url::to(['product/view', 'id' => $id]) ?>"><?= $item['name']?></td>
                        <td><?= $item['size']?></td>
                        <td><?= $item['qty']?></td>
                        <td><?= $item['price']?></td>
                        <td><?= $item['price']*$item['qty'] ?></td>
                        <td><span data-id="<?= $id ?>" class="glyphicon glyphicon-remove text-danger del-item" aria-hidden="true"></span></td>
                    </tr>
                <?php endforeach; ?>
                <tr>
                    <td colspan="5">Итого: </td>
                    <td><?= $session['cart.qty']?> </td>

                </tr>
                <tr>
                    <td colspan="5">На сумму: </td>
                    <td><?= $session['cart.sum']?> </td>

                </tr>
                </tbody>
            </table>
        </div>
        <hr/>
        <?php $form = ActiveForm::begin() ?>
        <?= $form->field($order, 'firstname') ?>
        <?= $form->field($order, 'lastname') ?>

       <?php

//    $city_ref = '000655d4-4079-11de-b509-001d92f78698';

//        $areasNp = NpAreas::find()->indexBy('ref')->asArray()->all();
//        $yyy = NpCities::find()->indexBy('area')->asArray()->one();
//        $warehousesNp = NpWarehouses::find()->where(['city_ref' => $city_ref])->asArray()->all();
//        $citiesNp = NpCities::find()->where(['area' => '71508140-9b87-11de-822f-000c2965ae0e'])->asArray()->all();


//        $regions  = City::find()->indexBy('region_id')->asArray()->all();
//        $cities = City::find()->indexBy('city_id')->asArray()->all();
//        $country = City::find()->indexBy('country_id')->asArray()->all();
        ?>
<!--        <pre> --><?php //print_r($yyy) ?><!--</pre>-->
<!--        <pre> --><?php //print_r($xxx) ?><!--</pre>-->
<!--        <pre> --><?php //print_r($zzz) ?><!--</pre>-->

        <?php
        $delivery = DeliveryType::find()->indexBy('delivery_id')->asArray()->all();
        $deliveryList = ArrayHelper::map($delivery, 'delivery_id', 'delivery_type');

//        $areasN = asort($catList);

        ?>
        <?= $form->field($order, 'delivery_id')->dropDownList($deliveryList, ['id' => 'del-id', 'prompt' => '-- Оберіть спосіб діставки --']); ?>
<?php



        $areaList = [];
        echo $form->field($order, 'area_id')->widget(DepDrop::classname(), [
            'options' => ['id' => 'area-id'],
            'data' => $areaList,
            'pluginOptions' => [
                'depends' => ['del-id'],
                'placeholder' => 'Область...',
                'url' => Url::to(['area'])
            ]
        ]);


        $subcatList = [];

    echo $form->field($order, 'city_id')->widget(DepDrop::classname(), [
        'options' => ['id' => 'subcat-id'],
        'data' => $subcatList,
        'pluginOptions' => [
            'depends' => ['del-id', 'area-id'],
            'placeholder' => 'Місто...',
            'url' => Url::to(['city'])
        ]
    ]);

    $warehouseList = [];

    echo $form->field($order, 'site_key')->widget(DepDrop::classname(), [
        'options' => ['id' => 'warehouse-id'],
        'data' => $warehouseList,
        'pluginOptions'=>[
            'depends'=>['del-id', 'area-id', 'subcat-id'],
            'placeholder'=>'Відділення...',
            'url' => Url::to(['warehouse'])
        ]
    ]);

                        /***  Укр пошта ***/


        $area2List = [];
        echo $form->field($order, 'area_id')->widget(DepDrop::classname(), [
            'options' => ['id' => 'area-two-id'],
            'data' => $area2List,
            'pluginOptions' => [
                'depends' => ['del-id'],
                'placeholder' => 'Область...',
                'url' => Url::to(['area-two'])
            ]
        ]);

        $region2List = [];
        echo $form->field($order, 'region_id')->widget(DepDrop::classname(), [
            'options' => ['id' => 'region-two-id'],
            'data' => $region2List,
            'pluginOptions' => [
                'depends' => ['del-id', 'area-two-id'],
                'placeholder' => 'Район...',
                'url' => Url::to(['region-two'])
            ]
        ]);


        $city2List = [];

        echo $form->field($order, 'city_id')->widget(DepDrop::classname(), [
            'options' => ['id' => 'city-two-id'],
            'data' => $city2List,
            'pluginOptions' => [
                'depends' => ['del-id', 'area-two-id', 'region-two-id'],
                'placeholder' => 'Населений пункт...',
                'url' => Url::to(['city-two'])
            ]
        ]);


    /***  ***/








?>








<!--        --><?php //if (isset($country)): ?>
<!--            <div class="form-group field-ordercontacts-country_id has-success">-->
<!--                <label class="control-label" for="ordercontacts-country_id">Страна  </label>-->
<!--                <select id="ordercontacts-country_id" class="form-control" name="OrderContacts[country_id]" aria-invalid="false">-->
<!--                    --><?php //foreach ($country as $item):?>
<!--                    <option value="--><?//= $item['country_id']?><!--">--><?//= $item['country_name']?><!--</option>-->
<!--                    --><?php //endforeach;?>
<!--                </select>-->
<!--            </div><br>-->
<!--        --><?php //endif; ?>
<!---->
<!--        --><?php //if (isset($regions)): ?>
<!--            <div class="form-group field-ordercontacts-region_id required has-success">-->
<!--                <label class="control-label" for="ordercontacts-region_id">Область </label>-->
<!--                <select id="ordercontacts-region_id" class="form-control" name="OrderContacts[region_id]" aria-invalid="false">-->
<!--                    --><?php //foreach ($regions as $item):?>
<!--                        <option value="--><?//= $item['region_id']?><!--">--><?//= $item['region_name']?><!--</option>-->
<!--                    --><?php //endforeach;?>
<!--                </select>-->
<!--            </div><br>-->
<!--        --><?php //endif; ?>
<!---->
<!--        --><?php //if (isset($cities)): ?>
<!--    <div class="form-group field-ordercontacts-city_id required has-success">-->
<!--        <label class="control-label" for="ordercontacts-city_id">Город     </label>-->
<!--        <select  id="ordercontacts-city_id" class="form-control" name="OrderContacts[city_id]" aria-invalid="false">-->
<!--                --><?php //foreach ($cities as $item):?>
<!--                        <option value="--><?//= $item['city_id']?><!--">--><?//= $item['city_name']?><!--</option>-->
<!--                    --><?php //endforeach;?>
<!--                </select>-->
<!--            </div><br>-->
<!--        --><?php //endif; ?>
<!---->
<!--        --><?php //if (isset($areasNp)): ?>
<!--            <div class="form-group field-np-areas-ref required has-success">-->
<!--                <label class="control-label" for="np_areas-ref">Область </label>-->
<!--                <select id="np_areas-ref" class="form-control" name="NpAreas[ref]" aria-invalid="false">-->
<!--                    --><?php //foreach ($areasNp as $item):?>
<!--                        <option value="--><?//= $item['ref']?><!--">--><?//= $item['description']?><!--</option>-->
<!--                    --><?php //endforeach;?>
<!--                </select>-->
<!--            </div><br>-->
<!--        --><?php //endif; ?>
<!---->
<!--        --><?php //if (isset($citiesNp)): ?>
<!--            <div class="form-group field-np-areas-ref required has-success">-->
<!--                <label class="control-label" for="np_areas-ref">Місто </label>-->
<!--                <select id="np_areas-ref" class="form-control" name="NpAreas[ref]" aria-invalid="false">-->
<!--                    --><?php //foreach ($citiesNp as $item):?>
<!--                        <option value="--><?//= $item['ref']?><!--">--><?//= $item['description']?><!--</option>-->
<!--                    --><?php //endforeach;?>
<!--                </select>-->
<!--            </div><br>-->
<!--        --><?php //endif; ?>
<!---->
<!--        --><?php //if (isset($warehousesNp)): ?>
<!--            <div class="form-group field-np-areas-ref required has-success">-->
<!--                <label class="control-label" for="np_areas-ref">Відділення </label>-->
<!--                <select id="np_areas-ref" class="form-control" name="NpAreas[ref]" aria-invalid="false">-->
<!--                    --><?php //foreach ($warehousesNp as $item):?>
<!--                        <option value="--><?//= $item['ref']?><!--">--><?//= $item['description']?><!--</option>-->
<!--                    --><?php //endforeach;?>
<!--                </select>-->
<!--            </div><br>-->
<!--        --><?php //endif; ?>




        <?= $form->field($order, 'email') ?>
        <?= $form->field($order, 'phone') ?>
        <?= $form->field($order, 'address')->textInput(['maxlength' => true]) ?>
        <?= $form->field($order, 'additional_info')->textarea(['rows' => 6]) ?>

        <?= Html::submitButton('Заказать', ['class' => 'btn btn-success'] ) ?>
        <?php $form = ActiveForm::end() ?>

    <?php else: ?>
        <h3>Корзина пуста</h3>
    <?php endif; ?>


    <script>     $('.del-item').on('click', function() {
            var id = $(this).data('id');
            console.log(id);
            $.ajax({
                url: '/cart/del-item',
                data: {id: id},
                type: 'GET',
                success: function (res) {
                    if (!res) alert('Ошибка!');
                    console.log(res);
                    showCart(res);
                },
                error: function () {
                    alert('Error!');
                }
            });
        });</script>
</div>